#!/usr/bin/env bash
# Written in [Amber](https://amber-lang.com/)
# version: 0.3.4-alpha
# date: 2024-08-13 15:07:06
__0_a=12
# This is a test
if [ $(echo ${__0_a} '>' 0 | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//') != 0 ]; then
    echo $(echo  '-' ${__0_a} | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
fi