// Check if such directory exists
$ test -f "Cargo.toml" > /dev/null $ failed {
    echo "Please run this command in the project root directory"
    trust $ exit 1 $
}

trust {
    if status == 0 {
        // Recompile installer scripts
        $ cargo run -- setup/install.ab setup/install.sh $
        $ cargo run -- setup/uninstall.ab setup/uninstall.sh $
    } else {
        echo "Please run this command in the project root directory"
    }
}
