#!/usr/bin/env bash
# Written in [Amber](https://amber-lang.com/)
# version: 77b6aa9
# Output
# 39
# 58
# 27.8
# 602.66
foo__0_v0() {
    local a_3="${1}"
    local b_4="${2}"
    eval "${a_3}=\"\$(( \${!a_3} + b_4 ))\""
}

foo__0_v1() {
    local a_13="${1}"
    local b_14="${2}"
    eval "${a_13}=\"$(eval "echo \"\${!a_13}\" '+' \"\${b_14}\" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//'")\""
}

bar__1_v0() {
    local a_9="${1}"
    local b_10="${2}"
    local c_11="${3}"
    eval "${a_9}=\"\$(( \$(( \${!a_9} + b_10 )) + c_11 ))\""
}

bar__1_v1() {
    local a_16="${1}"
    local b_17="${2}"
    local c_18="${3}"
    eval "${a_16}=\"$(eval "echo \"$(eval "echo \"\${!a_16}\" '+' \"\${b_17}\" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//'")\" '+' \"\${c_18}\" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//'")\""
}

a_0=15
foo__0_v0 "a_0" 24
echo "${a_0}"
b_5=4
bar__1_v0 "b_5" 12 42
echo "${b_5}"
a_12=15.15
foo__0_v1 "a_12" 12.65
echo "${a_12}"
b_15=23.65
bar__1_v1 "b_15" 32.67 546.34
echo "${b_15}"
