// Output
// Gt and Ge
// Ge: 1
// Gt: 1
// Le: 0
// Lt: 0
// Ge and Le (equality)
// Ge: 1
// Gt: 0
// Le: 1
// Lt: 0
// Lt and Le
// Ge: 0
// Gt: 0
// Le: 1
// Lt: 1

const left = [11.11, 11.11, 11.11]
const right = [9.9, 9.9, 9.9]

echo("Gt and Ge")
echo("Ge: {left >= right}")
echo("Gt: {left > right}")
echo("Le: {left <= right}")
echo("Lt: {left < right}")

const left = [3.14, 9.81, 2.71]
const right = [3.14, 9.81, 2.71]

echo("Ge and Le (equality)")
echo("Ge: {left >= right}")
echo("Gt: {left > right}")
echo("Le: {left <= right}")
echo("Lt: {left < right}")

const left = [15.15, 20.20, 20.50]
const right = [15.15, 20.20, 25.00]

echo("Lt and Le")
echo("Ge: {left >= right}")
echo("Gt: {left > right}")
echo("Le: {left <= right}")
echo("Lt: {left < right}")
