// Output
// Values at -1..0: []
// Values at -1..1: [apple]
// Values at -1..2: [apple banana]
// Values at -1..3: [apple banana cherry]
// Values at -1..4: [apple banana cherry]
// Values at 0..0: []
// Values at 0..1: [apple]
// Values at 0..2: [apple banana]
// Values at 0..3: [apple banana cherry]
// Values at 0..4: [apple banana cherry]
// Values at 1..0: []
// Values at 1..1: []
// Values at 1..2: [banana]
// Values at 1..3: [banana cherry]
// Values at 1..4: [banana cherry]
// Values at 2..0: []
// Values at 2..1: []
// Values at 2..2: []
// Values at 2..3: [cherry]
// Values at 2..4: [cherry]
// Values at 3..0: []
// Values at 3..1: []
// Values at 3..2: []
// Values at 3..3: []
// Values at 3..4: []
// Values at 4..0: []
// Values at 4..1: []
// Values at 4..2: []
// Values at 4..3: []
// Values at 4..4: []
// Values at -1..=-1: []
// Values at -1..=0: [apple]
// Values at -1..=1: [apple banana]
// Values at -1..=2: [apple banana cherry]
// Values at -1..=3: [apple banana cherry]
// Values at 0..=-1: []
// Values at 0..=0: [apple]
// Values at 0..=1: [apple banana]
// Values at 0..=2: [apple banana cherry]
// Values at 0..=3: [apple banana cherry]
// Values at 1..=-1: []
// Values at 1..=0: []
// Values at 1..=1: [banana]
// Values at 1..=2: [banana cherry]
// Values at 1..=3: [banana cherry]
// Values at 2..=-1: []
// Values at 2..=0: []
// Values at 2..=1: []
// Values at 2..=2: [cherry]
// Values at 2..=3: [cherry]
// Values at 3..=-1: []
// Values at 3..=0: []
// Values at 3..=1: []
// Values at 3..=2: []
// Values at 3..=3: []
// Values at 4..=-1: []
// Values at 4..=0: []
// Values at 4..=1: []
// Values at 4..=2: []
// Values at 4..=3: []

fun test_range(ref array) {
    for begin in -1..=4 {
        for end in 0..=4 {
            echo "Values at {begin}..{end}: [{array[begin..end]}]"
        }
    }
    for begin in -1..=4 {
        for end in -1..=3 {
            echo "Values at {begin}..={end}: [{array[begin..=end]}]"
        }
    }
}

main {
    let data = ["apple", "banana", "cherry"]
    test_range(data)
}
