// Output
// Value at -4: "zero"
// Value at -3: "one"
// Value at -2: "two"
// Value at -1: "three"

fun test_index(array) {
    for index in -4..=-1 {
        echo("Value at {index}: \"{array[index]}\"")
    }
}

main {
    if shellname() == "bash" and shellversion() < [4, 3] {
        echo("Succeeded")
        exit(0)
    }
    const array = ["zero", "one", "two", "three"]
    test_index(array)
}
