// Output
// Value at -4: "zero"
// Value at -3: "one"
// Value at -2: "two"
// Value at -1: "three"

main {
    if shellname() == "bash" and shellversion() < [4, 3] {
        echo("Succeeded")
        exit(0)
    }
    const array = ["zero", "one", "two", "three"]
    echo("Value at -4: \"{array[-4]}\"")
    echo("Value at -3: \"{array[-3]}\"")
    echo("Value at -2: \"{array[-2]}\"")
    echo("Value at -1: \"{array[-1]}\"")
}
