// Output
// Value at -5: ""
// Value at -4: "zero"
// Value at -3: "one"
// Value at -2: "two"
// Value at -1: "three"
// Value at 0: "zero"
// Value at 1: "one"
// Value at 2: "two"
// Value at 3: "three"
// Value at 4: ""

fun test_index(inner) {
    for index in -5..=4 {
        echo "Value at {index}: \"{inner[index]}\""
    }
}

main {
    let data = ["zero", "one", "two", "three"]
    test_index(data)
}
