// Output
// Command line parser
// Syntax: script.ab [options]
//   TEXT: Text .......... Positional text
//   NUMBER: Num ......... Positional number
//   ARRAY: [Text] ....... Positional array
//   -t|--text: Text ..... Optional text
//   -n|--number: Num .... Optional number
//   -f|--flag: Bool ..... Optional flag
//   -i|--invert: Bool ... Optional invert
//   -a|--array: [Num] ... Optional array
//   --help .............. Show help text

let parser = parser("Command line parser")
let positional_text = param(parser, "text", "Hello world", "Positional text")
let positional_number = param(parser, "number", 42, "Positional number")
let positional_array = param(parser, "array", ["foo", "bar", "baz"], "Positional array")
let optional_text = param(parser, "-t|--text", "Lorem ipsum", "Optional text")
let optional_number = param(parser, "-n|--number", 0.001, "Optional number")
let optional_false = param(parser, "-f|--flag", false, "Optional flag")
let optional_true = param(parser, "-i|--invert", true, "Optional invert")
let optional_array = param(parser, "-a|--array", [101, 102, 103], "Optional array")

let args = ["./script.ab", "--help"]
getopt(parser, args)
