// Output
// Positional text: Hello world
// Positional number: 42
// Positional array: foo bar baz
// Optional text: Lorem ipsum
// Optional number: 0.001
// Optional flag: 0
// Optional invert: 1
// Optional array: 101 102 103

let parser = parser("Command line parser")
let positional_text = param(parser, "text", "Hello world", "Positional text")
let positional_number = param(parser, "number", 42, "Positional number")
let positional_array = param(parser, "array", ["foo", "bar", "baz"], "Positional array")
let optional_text = param(parser, "-t|--text", "Lorem ipsum", "Optional text")
let optional_number = param(parser, "-n|--number", 0.001, "Optional number")
let optional_false = param(parser, "-f|--flag", false, "Optional flag")
let optional_true = param(parser, "-i|--invert", true, "Optional invert")
let optional_array = param(parser, "-a|--array", [101, 102, 103], "Optional array")

let args = ["./script.ab"]
getopt(parser, args)

echo "Positional text: {positional_text}"
echo "Positional number: {positional_number}"
echo "Positional array: {positional_array}"
echo "Optional text: {optional_text}"
echo "Optional number: {optional_number}"
echo "Optional flag: {optional_false}"
echo "Optional invert: {optional_true}"
echo "Optional array: {optional_array}"
