main {
    trust silent $ killall yes $ // Cleanup before test

    trust $ yes > /dev/null 2>&1 & $
    const first_pid = pid()
    disown(first_pid)

    // ksh keeps disowned processes visible in its jobs table.
    if shellname() == "ksh" or len($ jobs -l $?) == 0 {
        trust $ yes > /dev/null 2>&1 & $
        const second_pid = pid()

        trust $ yes > /dev/null 2>&1 & $
        const third_pid = pid()
        disown([second_pid, third_pid])

        if shellname() == "ksh" or len($ jobs -l $?) == 0 {
            echo("Succeeded")
        } else {
            echo("Process still owned")
        }
        trust silent $ kill {second_pid} {third_pid} $
    } else {
        echo("Process still owned")
    }

    trust silent $ kill {first_pid} $ // Cleanup after test
}
