import { math_sum } from "std/math"

// Output
// Requirements not met

let requirements = [true, true, true]

main {
    silent {
        $ seq 1 $ failed: requirements[0] = false
        $ ls $ failed: requirements[1] = false
        $ you_do_not_have_this $ failed: requirements[2] = false
    }

    if math_sum(requirements as [Num]) == 3 {
        echo "All requirements are met"
    } else {
        echo "Requirements not met"
        fail
    }
}
