// Output
// Generic
// Number
// Text

fun return_generic(): [] {
        return ["the great unknown"]
}

fun test_func(arr: []) {
        if arr is [] {
                echo "Generic"
        }

        if arr is [Int] {
                echo "Number"
        }

        if arr is [Text] {
                echo "Text"
        }
}

test_func(return_generic())
test_func([42, 69])
test_func(["Hello", "Hi"])
