import * from "std/text"

// Output
// ===
// ===
// ===

main {
    let tmpdir = unsafe $ mktemp -d $
    unsafe {
        $ touch {tmpdir}/1st\ file\ with\ spaces.txt $
        $ touch {tmpdir}/2nd\ file\ with\ spaces.txt $
        $ touch {tmpdir}/file1.txt $
        $ touch {tmpdir}/file2.txt $
        $ touch {tmpdir}/other1.csv $
        $ touch {tmpdir}/other2.csv $
    }
    cd tmpdir

    echo "==="
    loop file in glob("missing*") {
        echo file
    }
    echo "==="
    loop index, file in glob("missing*") {
        echo "{index}: {file}"
    }
    echo "==="

    unsafe $ rm -rf {tmpdir} $
}
