import * from "std/text"

// Output
// ===
// file1.txt
// file2.txt
// other1.csv
// other2.csv
// ===
// 0: file1.txt
// 1: file2.txt
// 2: other1.csv
// 3: other2.csv
// ===

main {
    let tmpdir = unsafe $ mktemp -d $
    unsafe {
        $ touch {tmpdir}/1st\ file\ with\ spaces.txt $
        $ touch {tmpdir}/2nd\ file\ with\ spaces.txt $
        $ touch {tmpdir}/file1.txt $
        $ touch {tmpdir}/file2.txt $
        $ touch {tmpdir}/other1.csv $
        $ touch {tmpdir}/other2.csv $
    }
    cd tmpdir

    echo "==="
    loop file in glob("missing*", "file*", "*.csv") {
        echo file
    }
    echo "==="
    loop index, file in glob("missing*", "file*", "*.csv") {
        echo "{index}: {file}"
    }
    echo "==="

    unsafe $ rm -rf {tmpdir} $
}
