import * from "std/text"

// Output
// ===
// /tmp/tmpdir/missing*
// /tmp/tmpdir/file1.txt
// /tmp/tmpdir/file2.txt
// /tmp/tmpdir/other1.csv
// /tmp/tmpdir/other2.csv
// ===
// 0: /tmp/tmpdir/missing*
// 1: /tmp/tmpdir/file1.txt
// 2: /tmp/tmpdir/file2.txt
// 3: /tmp/tmpdir/other1.csv
// 4: /tmp/tmpdir/other2.csv
// ===

main {
    let tmpdir = unsafe $ mktemp -d $
    unsafe {
        $ touch {tmpdir}/1st\ file\ with\ spaces.txt $
        $ touch {tmpdir}/2nd\ file\ with\ spaces.txt $
        $ touch {tmpdir}/file1.txt $
        $ touch {tmpdir}/file2.txt $
        $ touch {tmpdir}/other1.csv $
        $ touch {tmpdir}/other2.csv $
    }

    echo "==="
    loop file in glob("{tmpdir}/missing*", "{tmpdir}/file*", "{tmpdir}/*.csv") {
        file = replace_regex(file, tmpdir, "/tmp/tmpdir", true)
        echo file
    }
    echo "==="
    loop index, file in glob("{tmpdir}/missing*", "{tmpdir}/file*", "{tmpdir}/*.csv") {
        file = replace_regex(file, tmpdir, "/tmp/tmpdir", true)
        echo "{index}: {file}"
    }
    echo "==="

    unsafe $ rm -rf {tmpdir} $
}
