import * from "std/text"

// Output
// ===
// /tmp/tmpdir/1st file with spaces.txt
// /tmp/tmpdir/2nd file with spaces.txt
// ===
// 0: /tmp/tmpdir/1st file with spaces.txt
// 1: /tmp/tmpdir/2nd file with spaces.txt
// ===

main {
    let tmpdir = unsafe $ mktemp -d $
    unsafe {
        $ touch {tmpdir}/1st\ file\ with\ spaces.txt $
        $ touch {tmpdir}/2nd\ file\ with\ spaces.txt $
        $ touch {tmpdir}/file1.txt $
        $ touch {tmpdir}/file2.txt $
        $ touch {tmpdir}/other1.csv $
        $ touch {tmpdir}/other2.csv $
    }

    echo "==="
    loop file in glob("{tmpdir}/*with spaces*") {
        file = replace_regex(file, tmpdir, "/tmp/tmpdir", true)
        echo file
    }
    echo "==="
    loop index, file in glob("{tmpdir}/*with spaces*") {
        file = replace_regex(file, tmpdir, "/tmp/tmpdir", true)
        echo "{index}: {file}"
    }
    echo "==="

    unsafe $ rm -rf {tmpdir} $
}
