import { temp_dir_create } from "std/fs"

// Output
// [one]
// [two three four]
// []
// [five]
// [  six  ]

fun append_ref(ref inner: [Text], path: Text): Null {
    inner += lines(path)
}

main {
    const tmpdir = temp_dir_create("amber-XXXX", true, true)?
    trust $ echo -e 'one\ntwo three four' >{tmpdir}/numbers1.txt $
    trust $ echo -e '\nfive\n  six  ' >{tmpdir}/numbers2.txt $

    // Inefficient for large files.
    let lines_contents = lines("{tmpdir}/numbers1.txt")
    append_ref(lines_contents, "{tmpdir}/numbers2.txt")
    for line in lines_contents {
        echo("[{line}]")
    }
}
