import { temp_dir_create } from "std/fs"

// Output
// [one]
// [two three four]
// []
// [five]
// [  six  ]

main {
    const tmpdir = temp_dir_create("amber-XXXX", true, true)?
    trust $ echo -e 'one\ntwo three four' >{tmpdir}/numbers1.txt $

    // Inefficient for large files.
    const lines_contents = lines("{tmpdir}/numbers1.txt") + ["", "five", "  six  "]
    for line in lines_contents {
        echo("[{line}]")
    }
}
