import { temp_dir_create } from "std/fs"

// Output
// [one]
// [two three four]
// []
// [five]
// [  six  ]

main {
    const tmpdir = temp_dir_create("amber-XXXX", true, true)?
    trust $ echo -e 'one\ntwo three four\n\nfive\n  six  ' >{tmpdir}/numbers.txt $

    // Inefficient for large files.
    let lines_contents = ["a", "b", "c"]
    lines_contents = lines("{tmpdir}/numbers.txt")
    for line in lines_contents {
        echo("[{line}]")
    }
}
