import { temp_dir_create } from "std/fs"

// Output
// [one]
// [two three four]
// []
// [five]
// [  six  ]

main {
    const tmpdir = temp_dir_create("amber-XXXX", true, true)?
    trust $ echo -e '\nfive\n  six  ' >{tmpdir}/numbers2.txt $

    // Inefficient for large files.
    const lines_contents = ["one", "two three four"] + lines("{tmpdir}/numbers2.txt")
    for line in lines_contents {
        echo("[{line}]")
    }
}
