import { temp_dir_create } from "std/fs"

// Output
// [one]
// [two three four]
// []
// [five]
// [  six  ]

fun set_ref(ref inner: [Text], path: Text): Null {
    inner = lines(path)
}

main {
    const tmpdir = temp_dir_create("amber-XXXX", true, true)?
    trust $ echo -e 'one\ntwo three four\n\nfive\n  six  ' >{tmpdir}/numbers.txt $

    // Inefficient for large files.
    let lines_contents = ["a", "b", "c"]
    set_ref(lines_contents, "{tmpdir}/numbers.txt")
    for line in lines_contents {
        echo("[{line}]")
    }
}
