import * from "std/fs"

// Output
// .b
// a
// c
// a
// c
// .:
// a
// c
// ./a:
// a1

main {
    const tmpdir = temp_dir_create("amber-XXXX", true, true)?
    dir_create("{tmpdir}/a")?
    touch("{tmpdir}/a/a1")
    touch("{tmpdir}/.b")
    touch("{tmpdir}/c")
    for file in ls(tmpdir, true)? {
        echo(file)
    }
    cd(tmpdir)
    for file in ls()? {
        echo(file)
    }
    for file in ls(".", false, true)? {
        echo(file)
    }
}