import * from "std/fs"
import { array_contains } from "std/array"

// Output
// Succeeded

main {
    const tmpdir = temp_dir_create("amber-XXXX", true, true)?
    trust touch("{tmpdir}/file1.txt")
    trust touch("{tmpdir}/file2.txt")
    trust touch("{tmpdir}/other.csv")

    const files = ls("{tmpdir}/*.txt")?
    if array_contains(files, "{tmpdir}/file1.txt") and
       array_contains(files, "{tmpdir}/file2.txt") and
       not array_contains(files, "{tmpdir}/other.csv") {
        echo("Succeeded")
    } else {
        echo("Failed: {files}")
    }
}
