// Output
// 0 1 2 3 4 5 6 7 8 9
// 0 1 2 3 4 5 6 7 8 9 10
// ---
// -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8 9
// -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8 9 10
// ---
// -5 -4 -3 -2
// -5 -4 -3 -2 -1
// ---
// -5 -6 -7 -8 -9
// -5 -6 -7 -8 -9 -10
// ---
// 5 4 3 2 1 0 -1 -2 -3 -4 -5 -6 -7 -8 -9
// 5 4 3 2 1 0 -1 -2 -3 -4 -5 -6 -7 -8 -9 -10
// ---
// -5
// 0
// 5
// ---
// <3 empty lines>
//
//
//
// ---

const a = 0
const b = 10
echo(a..b)
echo(a..=b)
echo("---")

const a = -5
const b = 10
echo(a..b)
echo(a..=b)

echo("---")
const a = -5
const b = -1
echo(a..b)
echo(a..=b)

echo("---")
const a = -5
const b = -10
echo(a..b)
echo(a..=b)

echo("---")
const a = 5
const b = -10
echo(a..b)
echo(a..=b)

echo("---")
const c = -5
echo(c..=c)

const c = 0
echo(c..=c)

const c = 5
echo(c..=c)
echo("---")

echo("<3 empty lines>")
const c = 0
echo(c..c)

const c = 5
echo(c..c)

const c = -5
echo(c..c)
echo("---")
