// Output
// Gt and Ge
// Ge: 1
// Gt: 1
// Le: 0
// Lt: 0
// Lt and Le
// Ge: 0
// Gt: 0
// Le: 1
// Lt: 1

{
  const left = "abcxyz"
  const right = "abc"

  echo("Gt and Ge")
  echo("Ge: {left >= right}")
  echo("Gt: {left > right}")
  echo("Le: {left <= right}")
  echo("Lt: {left < right}")
}

{
  const left = "abc"
  const right = "abdef"

  echo("Lt and Le")
  echo("Ge: {left >= right}")
  echo("Gt: {left > right}")
  echo("Le: {left <= right}")
  echo("Lt: {left < right}")
}
