// Output
// 5
// 4
// 4
// 4
// 0

fun sum(ref value) {
    value = 4
    value += 1
    echo value
}

fun sub(ref value) {
    value = 5
    value -= 1
    echo value
}

fun mul(ref value) {
    value = 4
    value *= 1
    echo value
}

fun div(ref value) {
    value = 4
    value /= 1
    echo value
}

fun mod(ref value) {
    value = 4
    value %= 1
    echo value
}

let value_a = 0
sum(value_a)
sub(value_a)
mul(value_a)
div(value_a)
mod(value_a)
