#!/usr/bin/env amber

import { file_glob } from "std/fs"
import { echo_colored } from "std/env"

echo("[ Generating documentation ]")

const files = file_glob("src/std/*.ab") failed {
    echo("Unable to glob files in 'src/std'")
}

echo_colored("Building project...", 36)
silent $ cargo build --release $ failed {
    echo("Building project failed")
    exit(1)
}

for file in files {
    silent $ ./target/release/amber docs --usage {file} $ exited(code): if {
        code == 0: echo_colored("Successfully generated for '{file}'", 32)
        code == 1: echo_colored("Docs gen failed for '{file}'", 31)
        code == 127: echo_colored("Cannot find compiled artifact './target/release/amber'", 31)
        else: echo_colored("Unknown error", 31)
    }
}
