import { split, split_lines, text_contains } from "std/text"
import { file_write, file_append, dir_exists, file_exists, dir_create } from "std/fs"

/// file_glob() with globstar option which is not support by stdlib.
/// https://github.com/amber-lang/amber/issues/650
fun file_globstar(path: Text): [Text]? {
    let temp_globstar_enabled = Bool
    // -q for quiet. the return status dicates whether the globstap is set or unset
    $ shopt -q globstar $ exited(code) {
        temp_globstar_enabled = code == 0
    }

    // -s for set
    silent trust $ shopt -s globstar $
    const files = $ eval "for file in {path}; do [ -e \\"\\\$file\\" ] && printf \"%s\\n\" \\"\\\$file\\"; done" $?

    if temp_globstar_enabled: silent trust $ shopt -s globstar $
    else: silent trust $ shopt -u globstar $
    return split_lines(files)
}

let path = "/tmp/amber-sc-tests"

if (not dir_exists(path)) {
    dir_create(path) failed {
        echo("Failed to create directory {path}")
        exit(1)
    }
}
trust $ cp -r "src/tests/stdlib/" {path} $
let report = "{path}/report.txt"
file_write(report, "Report for Shellcheck") failed {
    echo("Failed to write report file")
    exit(1)
}
let output = ""

let stdtests = trust $ /usr/bin/ls "src/tests/stdlib/" $
let stdlib = split(stdtests, "\n")

for v in stdlib {
    if not text_contains(v, ".txt") and file_exists("src/tests/stdlib/{v}") {
        echo("Generating Bash script for test {v}")
        trust $ ./target/debug/amber build "src/tests/stdlib/{v}" "{path}/{v}.sh" $
        
        $ shellcheck "{path}/{v}.sh" $ exited(code) {
            if code != 0 {
                echo("Shellcheck found something!")
                file_append(report, "\n--- Issues in {v} ---\n") failed {
                    echo("Failed to append to report")
                }
            }
        }
    }
}
