import { array_search } from "std/array"

// Output
// Indices of "zero": [0 6]
// Indices of "one": [1 5]
// Indices of "two": [2 4]
// Indices of "three": [3]
// Indices of "four": []

fun test_search(inner: [Text], value: Text): Null {
    let indices = array_search(inner, value)
    echo "Indices of \"{value}\": [{indices}]"
}

main {
    let data = ["zero", "one", "two", "three", "two", "one", "zero"]
    test_search(data, "zero")
    test_search(data, "one")
    test_search(data, "two")
    test_search(data, "three")
    test_search(data, "four")
}
