import { remove_at } from "std/array"

// Output
// Array after -5: (4) [apple banana cherry date]
// Array after -4: (4) [apple banana cherry date]
// Array after -3: (4) [apple banana cherry date]
// Array after -2: (4) [apple banana cherry date]
// Array after -1: (4) [apple banana cherry date]
// Array after 0: (3) [banana cherry date]
// Array after 1: (3) [apple cherry date]
// Array after 2: (3) [apple banana date]
// Array after 3: (3) [apple banana cherry]
// Array after 4: (4) [apple banana cherry date]

fun test_remove(inner: [Text], index: Num): Null {
    let value = remove_at(inner, index)
    echo "Array after {index}: ({len(inner)}) [{inner}]"
}

main {
    let data = ["apple", "banana", "cherry", "date"]
    for index in -5..=4 {
        test_remove(data, index)
    }
}
