import { array_extract_at } from "std/array"

// Output
// Value at 0: "zero" (3) [one two three]
// Value at 1: "one" (3) [zero two three]
// Value at 2: "two" (3) [zero one three]
// Value at 3: "three" (3) [zero one two]

fun test_extract(data: [Text], index: Int): Null? {
    const value = array_extract_at(data, index)?
    echo "Value at {index}: \"{value}\" ({len(data)}) [{data}]"
}

main {
    const numbers = ["zero", "one", "two", "three"]
    for index in 0..4 {
        test_extract(numbers, index)?
    }
}
