import { first } from "std/array"

// Output
// First of array: "apple", [apple banana cherry date]
// First of empty: "", []

fun test_first(label: Text, array: [Text]): Null {
    let value = first(array)
    echo "First of {label}: \"{value}\", [{array}]"
}

main {
    let array = ["apple", "banana", "cherry", "date"]
    let empty = [Text]
    test_first("array", array)
    test_first("empty", empty)
}
