import { array_last } from "std/array"

// Output
// Last of numbers: "three" (4) [zero one two three]
// Last of empty array does not exist

fun test_last(label: Text, data: [Text]): Null {
    const value = array_last(data) failed {
        echo("Last of empty array does not exist")
        return null
    }
    echo("Last of {label}: \"{value}\" ({len(data)}) [{data}]")
}

main {
    const numbers = ["zero", "one", "two", "three"]
    const empty = [Text]
    test_last("numbers", numbers)
    test_last("empty", empty)
}
