import { array_index } from "std/array"

// Output
// Index of "zero": 0
// Index of "one": 1
// Index of "two": 2
// Index of "three": 3
// Index of "four": -1

fun test_index(array: [Text], value: Text): Null {
    let index = array_index(array, value)
    echo "Index of \"{value}\": {index}"
}

main {
    let array = ["zero", "one", "two", "three", "two", "one", "zero"]
    test_index(array, "zero")
    test_index(array, "one")
    test_index(array, "two")
    test_index(array, "three")
    test_index(array, "four")
}
