import { pop } from "std/array"

// Output
// Popped from data: "three" (3) [zero one two]
// Popped from empty: "" (0) []

fun test_pop(label: Text, inner: [Text]): Null {
    let value = pop(inner)
    echo "Popped from {label}: \"{value}\" ({len(inner)}) [{inner}]"
}

main {
    let data = ["zero", "one", "two", "three"]
    let empty = [Text]
    test_pop("data", data)
    test_pop("empty", empty)
}
