import { sorted } from "std/array"

// Output
// Array length: 6
// [-5 10 6 a c d]
// Array length: 6
// [6 10 a c d -5]
// Array length: 6
// [-5 d c a 10 6]
// Array length: 4
// [-2 10 5 7]
// Array length: 4
// [7 5 10 -2]
// Array length: 4
// [-2 5 7 10]
// Array length: 4
// [-5.4 11.5 2.34 6.1]
// Array length: 4
// [-5.4 2.34 6.1 11.5]
// Array length: 2
// [0 1]
// Array length: 2
// [ ]

fun test_sorted(arr: [], human: Bool, desc: Bool) {
    const result = sorted(arr, human, desc)
    echo("Array length: {len(result)}")
    echo("[{result}]")
}

main {
    test_sorted(["c", "d", "a", "10", "6", "-5"], false, false)
    test_sorted(["c", "d", "a", "10", "6", "-5"], true, false)
    test_sorted(["c", "d", "a", "10", "6", "-5"], true, true)
    test_sorted([7, 10, 5, -2], false, false)
    test_sorted([7, 10, 5, -2], false, true)
    test_sorted([7, 10, 5, -2], true, false)
    test_sorted([11.5, 6.1, -5.4, 2.34], false, false)
    test_sorted([11.5, 6.1, -5.4, 2.34], true, false)
    test_sorted([true, false], false, false)
    test_sorted([null, null], false, false)
}
