import { array_pop } from "std/array"

// Output
// Popped from numbers: "three" (3) [zero one two]
// Cannot pop from empty array

fun test_pop(label: Text, data: [Text]): Null {
    const value = array_pop(data) failed {
        echo("Cannot pop from empty array")
        return null
    }
    echo("Popped from {label}: \"{value}\" ({len(data)}) [{data}]")
}

main {
    const numbers = ["zero", "one", "two", "three"]
    const empty = [Text]
    test_pop("numbers", numbers)
    test_pop("empty", empty)
}
