import { first } from "std/array"

// Output
// First of data: "zero" (4) [zero one two three]
// First of empty: "" (0) []

fun test_first(label: Text, inner: [Text]): Null {
    let value = first(inner)
    echo "First of {label}: \"{value}\" ({len(inner)}) [{inner}]"
}

main {
    let data = ["zero", "one", "two", "three"]
    let empty = [Text]
    test_first("data", data)
    test_first("empty", empty)
}
