import { first } from "std/array"

// Output
// First of data: "apple" (4) [apple banana cherry date]
// First of empty: "" (0) []

fun test_first(label: Text, inner: [Text]): Null {
    let value = first(inner)
    echo "First of {label}: \"{value}\" ({len(inner)}) [{inner}]"
}

main {
    let data = ["apple", "banana", "cherry", "date"]
    let empty = [Text]
    test_first("data", data)
    test_first("empty", empty)
}
