import { array_search } from "std/array"

// Output
// Indices of "apple": [0 6]
// Indices of "banana": [1 5]
// Indices of "cherry": [2 4]
// Indices of "date": [3]
// Indices of "kiwi": []

fun test_search(inner: [Text], value: Text): Null {
    let indices = array_search(inner, value)
    echo "Indices of \"{value}\": [{indices}]"
}

main {
    let data = ["apple", "banana", "cherry", "date", "cherry", "banana", "apple"]
    test_search(data, "apple")
    test_search(data, "banana")
    test_search(data, "cherry")
    test_search(data, "date")
    test_search(data, "kiwi")
}
