import { change_owner } from "std/fs"
// We use `whoami` to get the running user to assign again the same user as permission
main {
    let tmpdir = $ mktemp -d /tmp/amber-XXXX $ failed {
        echo "It wasn't possible to create the folder"
    }
    $ touch {tmpdir}/amber-symbolic $ failed {
        echo "It wasn't possible to create {tmpdir}/amber-symbolic"
    }
    let owner = trust $ whoami $
    if change_owner("{tmpdir}/amber-symbolic", owner) {
        echo "Succeeded"
    } else {
        echo "File {tmpdir}/amber-symbolic not exists"
    }
    trust $ rm -rf {tmpdir} $
}
