import { take_option } from "std/cli"

// Output
// option absent
// option missing value
// option inline missing value

main {
    let args = ["build"]
    take_option(args, "--output") failed {
        echo("option absent")
    }

    args = ["build", "--output"]
    take_option(args, "--output") failed {
        echo("option missing value")
    }

    args = ["build", "--output="]
    take_option(args, "--output") failed {
        echo("option inline missing value")
    }
}
