import { contains_all } from "std/text"

// Output
// None: 0
// Left: 1
// Right: 1
// Both: 1

fun test_multiple(label, text, terms) {
    let result = contains_all(text, terms)
    echo "{label}: {result}"
}

main {
    test_multiple("None", "Hello World", ["Other", "Other"])
    test_multiple("Left", "Hello World", ["World", "Something"])
    test_multiple("Right", "Hello World", ["World", "Hello"])
    test_multiple("Both", "Hello World", ["Hello", "World"])
} 
