// Output
// Succeeded
// 2
import * from "std/fs"

main {
    const tmpdir = temp_dir_create("amber-XXXX", true, true)?
    cd(tmpdir)
    trust file_write("test.txt", "Succeeded")
    const f = file_read("test.txt") failed {
        echo("Failed")
    }
    echo(f)

    trust file_write("dash.txt", "-E")
    const d = file_read("dash.txt") failed {
        echo("Failed")
    }
    echo(len(d))
}
