import * from "std/fs"

main {
    const tmpdir = temp_dir_create("amber-XXXX", true, true)?
    trust {
        trust touch("{tmpdir}/1st file with spaces.txt")
        trust touch("{tmpdir}/2nd file with spaces.txt")
        trust touch("{tmpdir}/file.txt")
        trust touch("{tmpdir}/file1.txt")
        trust touch("{tmpdir}/file2.txt")
        trust touch("{tmpdir}/file99.txt")
        trust touch("{tmpdir}/other.csv")
    }
    trust cd(tmpdir)

    const files = file_glob("missing*")
    if len(files) == 0 {
        echo("Succeeded")
    }
    for file in files {
        echo("[{file}]")
    }
}
