import { file_chown, temp_dir_create } from "std/fs"

// We use `whoami` to get the running user to assign again the same user as permission
main {
    let tmpdir = temp_dir_create("amber-XXXX", true, true) failed {
        echo "It wasn't possible to create the folder"
    }
    $ touch {tmpdir}/amber-symbolic $ failed {
        echo "It wasn't possible to create {tmpdir}/amber-symbolic"
    }
    let owner = trust $ whoami $
    trust file_chown("{tmpdir}/amber-symbolic", owner)
    if status == 0 {
        echo "Succeeded"
    } else {
        echo "File {tmpdir}/amber-symbolic not exists"
    }
}
