// Output
// Succeeded
// Succeeded

import { dir_exists, file_compress, file_exists, file_extract, temp_dir_create } from "std/fs"

fun cleanup_dirs(dirs: [Text]): Null {
    for dir in dirs {
        if dir_exists(dir) {
            trust rm(dir, true, true)
        }
    }
}

fun verify_format(format: Text): Bool? {
    const created_src = temp_dir_create("amber-test-stdlib-fs_file_extract-{format}-src-XXXX", true, true) failed {
        echo("It is not possible to create the source directory")
        fail(1)
    }
    
    cd(created_src) failed {
        cleanup_dirs([created_src])
        echo("It is not possible to access the source directory")
        fail(2)
    }

    const test_file = "test.txt"

    touch(test_file) failed {
        cleanup_dirs([created_src])
        echo("It is not possible to create the test file")
        fail(3)
    }
    
    const compress_file = "compress.{format}"

    file_compress([test_file], compress_file) failed {
        cleanup_dirs([created_src])
        echo("It is not possible to create the compress \"{format}\" file")
        fail(4)
    }
    
    const created_dist = temp_dir_create("amber-test-stdlib-fs_file_extract-{format}-dist-XXXX", true, true) failed {
        cleanup_dirs([created_src])
        echo("It is not possible to create the destination directory")
        fail(5)
    }

    file_extract(compress_file, created_dist) failed {
        cleanup_dirs([created_src, created_dist])
        echo("It is not possible to extract the \"{format}\" file")
        fail(6)
    }

    const extracted = file_exists("{created_dist}/{test_file}")

    cleanup_dirs([created_src, created_dist])

    return extracted
}

main {
    const formats = ["tar.gz", "zip"]
    let all_extracted = true

    for format in formats {
        const extracted = verify_format(format) failed(error_code) {
            echo("{format}: Fail with error code: {error_code}")
        }

        if not extracted: all_extracted = false
        else: echo("Succeeded")
    }

    if not all_extracted {
        fail(1)
    }
}
