import * from "std/array"
import * from "std/fs"
import * from "std/text"

fun compare(actual: [Text], expected: [Text]): Bool {
    if len(actual) != len(expected) {
        return false
    }
    for file in expected {
        if not array_contains(actual, file) {
            return false
        }
    }
    return true
}

main {
    const tmpdir = temp_dir_create("amber-XXXX", true, true)?
    trust {
        trust touch("{tmpdir}/1st file with spaces.txt")
        trust touch("{tmpdir}/2nd file with spaces.txt")
        trust touch("{tmpdir}/file.txt")
        trust touch("{tmpdir}/file1.txt")
        trust touch("{tmpdir}/file2.txt")
        trust touch("{tmpdir}/file99.txt")
        trust touch("{tmpdir}/other.csv")
    }
    trust cd(tmpdir)

    const expected = [
        "1st file with spaces.txt",
        "2nd file with spaces.txt",
    ]
    const actual = file_glob("*with spaces*")
    if compare(actual, expected) {
        echo("Succeeded")
    } else {
        echo("Expected: {expected}")
        echo("Actual: {actual}")
    }
}
