// Output
// Succeeded
// 2

import * from "std/fs"

main {
    const tmpdir = temp_dir_create("amber-XXXX", true, true)?
    cd(tmpdir)
    touch("test.txt")
    trust file_append("test.txt", "Succeeded")
    const f = file_read("test.txt") failed {
        echo("Failed")
    }
    echo(f)

    touch("dash.txt")
    trust file_append("dash.txt", "-n")
    const d = file_read("dash.txt") failed {
        echo("Failed")
    }
    echo(len(d))
}
