import * from "std/fs"
import { array_contains } from "std/array"

main {
    const src_dir = temp_dir_create("amber-test-src-XXXX")?
    trust cd(src_dir)
    trust touch("test.txt")
    file_compress(["test.txt"],"filename.tar.gz")?
    const package = "{src_dir}/filename.tar.gz"
    if not file_exists(package) {
        echo("Compression falis; {package} does not exists")
    }

    const dist_dir = temp_dir_create("amber-test-dist-XXXX")?
    file_extract(package, dist_dir)?

    if file_exists("{dist_dir}/test.txt") {
        echo("Succeeded")
    } else {
        echo("Extraction fails: {dist_dir}/test.txt does not exist")
    }

    $ rm -rf {src_dir} {dist_dir} $?

    const src_dir2 = temp_dir_create("amber-test-zip-src-XXXX")?
    trust cd(src_dir2)
    trust touch("test.txt")
    const archive_path = "{src_dir2}/archive.zip"
    silent $ zip "{archive_path}" test.txt $?

    const dist_dir2 = temp_dir_create("amber-test-zip-dist-XXXX")?
    file_extract(archive_path, dist_dir2)?

    if file_exists("{dist_dir2}/test.txt") {
        echo("Succeeded")
    } else {
        echo("Extraction fails: {dist_dir2}/test.txt does not exist")
    }

    $ rm -rf {src_dir2} {dist_dir2} $?
}
