import * from "std/fs"

// Output
// [xxx; do echo HACKED; done; for file in]

main {
    const tmpdir = temp_dir_create("amber-XXXX", true, true)?
    trust {
        $ touch "{tmpdir}/xxx; do echo HACKED; done; for file in" $
    }
    cd tmpdir

    // The glob function escapes all characters in the passed-in glob
    // apart from "*", "?" and "/", to prevent injection attacks.  If we
    // didn't do this, the following code would output "[HACKED]" instead
    // of the filename.
    let files = file_glob("xxx; do echo HACKED; done; for file in") failed {
        echo "FAILED"
    }
    for file in files {
        echo "[{file}]"
    }
}
