import { symlink_create, temp_dir_create } from "std/fs"

// Output
// Succeeded
// Succeeded

main {
    const tmpdir = temp_dir_create("amber-XXXX", true, true)?
    touch("{tmpdir}/amber-symbolic")
    trust symlink_create("{tmpdir}/amber-symbolic", "{tmpdir}/amber-symbolic-link")
    if status == 0 {
        echo("Succeeded")
    } else {
        echo("failed")
    }
    touch("{tmpdir}/amber-symbolic")
    touch("{tmpdir}/amber-symbolic-link")
    trust symlink_create("{tmpdir}/amber-symbolic", "{tmpdir}/amber-symbolic-link")
    if status == 0 {
        echo("Succeeded")
    } else {
        echo("failed")
    }
} 
