import * from "std/fs"
import {split, starts_with} from "std/text"

fun filename(path: Text): Text {
    const parts = split(path, "/")
    return parts[len(parts) - 1]
}

main {
    const path = temp_dir_create("amber-XXXX")?
    const filename = filename(path)
    echo "{len(filename)} {len("amber-XXXX")} !=: {len(filename) != len("amber-XXXX")}"
    if {
        not starts_with(filename, "amber-") {
            echo "filename should start with \"amber-\", {filename} given"
        }
        len(filename) != len("amber-XXXX") {
            echo "The length of filename should be {len("amber-XXXX")}. {filename} given"
        }
        dir_exists(path) {
            echo "Succeeded"
        }
    }

    $ rmdir {path} $?
}
