import * from "std/fs"
import * from "std/text"

// Output
// *glob failed*

main {
    let tmpdir = trust $ mktemp -d $
    trust {
        $ touch {tmpdir}/1st\ file\ with\ spaces.txt $
        $ touch {tmpdir}/2nd\ file\ with\ spaces.txt $
        $ touch {tmpdir}/file.txt $
        $ touch {tmpdir}/file1.txt $
        $ touch {tmpdir}/file2.txt $
        $ touch {tmpdir}/file99.txt $
        $ touch {tmpdir}/other.csv $
    }

    let files = glob("{tmpdir}/missing*") failed {
        echo "*glob failed*"
    }
    loop file in files {
        file = replace_regex(file, tmpdir, "/tmp/tmpdir", true)
        echo "[{file}]"
    }

    trust $ rm -rf {tmpdir} $
}
