import { fetch } from "std/http"
import { match_regex } from "std/text"
main {
    if not match_regex(fetch("http://echo.free.beeceptor.com")?, "GET"): fail 1

    if not match_regex(fetch("http://echo.free.beeceptor.com", "POST")?, "POST"): fail 1

    if not match_regex(fetch("http://echo.free.beeceptor.com", "PUT")?, "PUT"): fail 1

    if not match_regex(fetch("http://echo.free.beeceptor.com", "DELETE")?, "DELETE"): fail 1

    echo "Succeeded"
}
