import { text_contains_all } from "std/text"

// Output
// None: 0
// One: 0
// Right: 1
// Both: 1

fun test_multiple(label, text, terms) {
    const result = text_contains_all(text, terms)
    echo("{label}: {result}")
}

main {
    test_multiple("None", "Hello World", ["Other", "Other"])
    test_multiple("One", "Hello World", ["World", "Something"])
    test_multiple("Right", "Hello World", ["World", "Hello"])
    test_multiple("Both", "Hello World", ["Hello", "World"])
} 
