import * from "std/text"

// Output
// aeon aeons ### eons
// abc[123]def
// ###
// .tar.gz
// #path#to#file.txt

main {
    echo(replace_regex("aeon aeons eon eons", " eon ", " ### "))
    // Combination of bracket exp and one or more
    echo(replace_regex("abc123def", "\([0-9][0-9]*\)", "[\1]"))
    // Ending position of the string
    echo(replace_regex("foo", "foo$", "###"))
    // A pipe (|) should be treated as a literal character in POSIX Standards BRE.
    echo(replace_regex(".tar.gz", "\.\(tar\.gz\|tgz\)$", "Failed"))
    // Replacing forward slash failed
    echo(replace_regex("/path/to/file.txt", "/", "#"))
}
