import { match_regex_any } from "std/text"

// Output
// Empty: 0
// None: 0
// Right: 1
// Left: 1
// Both: 1

fun test_multiple(label, text, terms) {
    const result = match_regex_any(text, terms)
    echo("{label}: {result}")
}

main {
    test_multiple("Empty", "Hello World", [Text])
    test_multiple("None", "Hello World", ["Other", "Other$"])
    test_multiple("Right", "Hello World", ["Other", "World$"])
    test_multiple("Left", "Hello World", ["^Hello", "Other"])
    test_multiple("Both", "Hello World", ["^Hello", "$World"])
}
