name: amber-bash
icon: assets/amber.png
title: Amber
base: core24
adopt-info: amber
summary: Amber the programming language compiled to bash
description: |
  Programming language that compiles to Bash. It's a high level programming language that makes it easy to create shell scripts.
  It's particularly well suited for cloud services.
contact: https://discord.com/invite/cjHjxbsDvZ
source-code: https://github.com/Ph0enixKM/Amber
issues: https://github.com/Ph0enixKM/Amber/issues
website: https://amber-lang.com/
grade: stable
confinement: strict
compression: lzo

parts:
  amber:
    plugin: rust
    source: .
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)


apps:
  amber:
    command: bin/amber
    plugs:
      - home
      - removable-media
